# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

management:
    context-path: /management

spring:
    application:
        name: slissek-pac
    datasource:
        platform: postgres
        url: jdbc:postgresql://localhost:5432/pac
        name:
        username: pac_app
        password: pac
    jpa:
        database: PostgreSQL
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        generate-ddl: true
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.cache.region.factory_class: com.prodyna.pac.voting.config.hazelcast.HazelcastCacheRegionFactory
            hibernate.cache.use_minimal_puts: true
            hibernate.cache.hazelcast.use_lite_member: true

server:
    port: 8080
    address: localhost

security:
    basic:
        enabled: false
    
voting:
    cache: # Hibernate 2nd level cache, used by CacheConfiguration
        timeToLiveSeconds: 3600
        hazelcast:
            backupCount: 1
    security:
        rememberMe:
            # security key (this key should be unique for your application, and kept secret)
            key: 62bf4948d723ea2c8629193b87069d216ff898b3
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx.enabled: true
